title: Tom's Blog
subtitle: Knowledge worth spreading
description: Learning by doing
keywords:
  - hexo
  - javascript
author: Tsung Yu Chen
language: en
timezone: ''
url: https://github.com/ChenTsungYu
root: /
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: true
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: ''
  wrap: true
  hljs: true
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: YYYY/MM/DD
time_format: HH:mm:ss
updated_option: false
per_page: 10
pagination_dir: page

logo:
    light: /img/dragon_blue.png
    dark: /img/dragon_red.png

theme: icarus
deploy:
  type: git
  repository: https://github.com/ChenTsungYu/ChenTsungYu.github.io.git
  branch: master
  message: Back up site