version: 5.1.0
variant: default

# Page metadata configurations
head:
    # URL or path to the website's icon
    # favicon: /img/dragon_red.png
    # Web application manifests configuration
    # https://developer.mozilla.org/en-US/docs/Web/Manifest
    manifest:
        name: 
        short_name: Tom
        start_url: 
        theme_color: 
        background_color: 
        display: standalone
        icons:
            -
                src: ''
                sizes: ''
                type: 
    open_graph:
        title: 
        type: blog
        url: 
        image: 
        site_name: 
        author: 
        description: 
        twitter_card: 
        twitter_id: 
        twitter_site: 
        google_plus: 
        fb_admins: 
        fb_app_id: 
    structured_data:
        title: 
        description: 
        url: 
        author: 
        publisher: 
        publisher_logo: 
        image: 
    meta:
        - ''
    rss: 
navbar:
    menu:
        Home: /
        Archives: /archives
        Categories: /categories
        Tags: /tags
        About: /about
    links:
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/ChenTsungYu
footer:
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/ChenTsungYu
article:
    highlight:
        theme: atom-one-dark
        clipboard: true
        fold: unfolded
    readtime: true
    update_time: false
search:
    type: insight
comment:
    type: gitalk
    client_id: 7913190f1a943b88e276
    client_secret: 8c54a86c8fe06b650efe932eb53bc421ddf84773
    repo: ChenTsungYu.github.io
    owner: ChenTsungYu
    admin:
        - ChenTsungYu
    per_page: 20
sidebar:
    left:
        sticky: true
    right:
        sticky: false
widgets:
    -
        position: left
        type: profile
        author: Tsung Yu Chen
        location: Taiwan
        avatar: 
        avatar_rounded: false
        gravatar: 
        social_links:
            Github:
                icon: fab fa-github
                url: https://github.com/ChenTsungYu
            Facebook:
                icon: fab fa-facebook
                url: https://www.facebook.com/zong.y.r/
            LinkedIn:
                icon: fab fa-linkedin-in
                url: https://www.linkedin.com/in/tom-chen-1012/
    -
        position: left
        type: toc
        index: true
        collapsed: true
        depth: 4
    -
        position: left
        type: recent_posts
plugins:
    animejs: true
    back_to_top: true
    baidu_analytics:
        tracking_id: 
    bing_webmaster:
        tracking_id: 
    busuanzi: false
    cnzz:
        id: 
        web_id: 
    cookie_consent:
        type: info
        theme: edgeless
        static: false
        position: bottom-left
        policyLink: https://www.cookiesandyou.com/
    gallery: true
    google_analytics:
        tracking_id: 
    hotjar:
        site_id: 
    katex: false
    mathjax: false
    outdated_browser: false
    progressbar: true
    statcounter:
        project: 
        security: 
    twitter_conversion_tracking:
        pixel_id: 
providers:
    cdn: jsdelivr
    fontcdn: google
    iconcdn: fontawesome
